# Generated by Django 5.0.2 on 2024-02-12 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="date",
        ),
    ]
