# Generated by Django 5.0.2 on 2024-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_remove_price_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='quality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
